#!/usr/bin/env python

import roslib
import rospy
import math
import actionlib
import numpy as np
import random
import trajectory_msgs.msg as tm
from std_msgs.msg import String, Float64MultiArray
from enum import Enum
from std_srvs.srv import Empty, EmptyResponse

    


class Swing:
    def __init__(self):
        self.joint_pub = rospy.Publisher('/gazebo_panda/effort_joint_position_controller/command', Float64MultiArray, queue_size=10)
        self.joint_names = rospy.get_param("/gazebo_panda/effort_joint_position_controller/joints")
        self.pub = rospy.Publisher('chatter', String, queue_size=10)
        print(self.joint_names)

        self.ready_srv = rospy.Service("ready", Empty, self.ready_callback)
        self.up_srv = rospy.Service("upswing", Empty, self.upswing_callback)
        self.up_srv = rospy.Service("hit", Empty, self.hit_callback)

        self.goal_pos = np.zeros(len(self.joint_names))
        self.joint_vel = np.zeros(len(self.joint_names))
        self.move = True

    def ready_callback(self, emp):
        self.goal_pos = [-1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 1.0]
        #self.joint_vel = [0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
        print("ready")
        return EmptyResponse()

    def upswing_callback(self, emp):
        self.goal_pos = [-2.0, 0.0, 0.0, -1.0, 0.0, 0.0, 1.0]
        print("up")
        return EmptyResponse()

    def hit_callback(self, emp):
        self.goal_pos = [1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 1.0]
        print("hit")
        return EmptyResponse()

    def move_to_pose(self):

        jt = Float64MultiArray()

        jt.data = self.goal_pos

        self.joint_pub.publish(jt)

        self.pub.publish("ok")


        self.move = False



def main():
    """ The main() function. """
    #ros node init

    rospy.init_node('swing')
    r = rospy.Rate(10)

    swing = Swing()

    while not rospy.is_shutdown():
        swing.move_to_pose()
        r.sleep()



if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
